### ISSUE TITLE
Changes to selectedIndex doesn't propagate to the DOM on Controlled Mode

### ISSUE THREAD

**Issue by canrozanes** [concordnow/ember-aria-tabs#244]
I have this case where the .hbs looks like this

```hbs
<AriaTabs @selectedIndex={{this.currentTabIndex}} @onSelect={{action this.selectTab}} @forceRenderTabPanel={{true}} as |at|>
  <at.tabList as |tl|>
    {{#each this.tabs as |tab index|}}
      <tl.tab>
        {{tab.name}}
      </tl.tab>
    {{/each}}
  </at.tabList>
  {{#each this.tabs as |tab index|}}
    <at.tabPanel>
      <p>Some Panel Logic here</p>
    </at.tabPanel>
  {{/each}}
</AriaTabs>
```

and 

```js
@action
  selectTab(index) {
    this.currentTabIndex = index;
  }
```

After I click a tab, from looking at the internals of AriaTabs through Ember Inspector, I can see that the this.args.selectedIndex gets updated, but those updates don't translate to the DOM and `--active` class stays in the previous tab.

I haven't also seen a full example of AriaTabs in controlled mode so perhaps I'm doing something wrong. What am I missing here?

**Comment by mayatron** [comment]
The issue here is that in controlled mode, the consuming application changes the `@selectedIndex` argument but that change is never reflected in `this.selectedIndex`, which needs to happen in order for the DOM updates to happen.
